### ISSUE TITLE
detachListeners not called

### ISSUE THREAD

**Issue by caesarsol** [mikolalysenko/mouse-change#2]
Is there something I'm missing, or is it right that the `detachListeners` function is not actually called on `enable = false`?

See https://github.com/mikolalysenko/mouse-change/blob/master/mouse-listen.js#L182

**Comment by mikolalysenko** [comment]
That's a bug

**Comment by mikolalysenko** [comment]
Thanks!  Fixed in https://github.com/mikolalysenko/mouse-change/commit/78fed9cabb647ba76247c3bf2295abac72c8a978
